# Opticks Config

#scl enable devtoolset-7 bash
export CXXFLAGS="$CXXFLAGS -fPIC"
export CFLAGS="$CFLAGS -fPIC"

opticks-(){  [ -r $HOME/opticks/opticks.bash ] && . $HOME/opticks/opticks.bash && opticks-env $* ; }
opticks-

o(){ opticks- ; cd $(opticks-home) ; git status ; }
oo(){ opticks- ; cd $(opticks-home) ; om- ; om-- ;  }
t(){ typeset -f $* ; }

# PATH envvars control the externals that opticks/CMake or pkg-config will find
unset CMAKE_PREFIX_PATH
unset PKG_CONFIG_PATH

export OPTICKS_EXTERNALS=${HOME}/opticks_externals

# mandatory envvars in buildenv
export OPTICKS_PREFIX=/home/opc/opticks.build
export OPTICKS_CUDA_PREFIX=/usr/local/cuda-11.1
export OPTICKS_OPTIX_PREFIX=${HOME}/NVIDIA/NVIDIA-OptiX-SDK-6.5.0-linux64
export OPTICKS_COMPUTE_CAPABILITY=60

## hookup paths to access "foreign" externals
opticks-prepend-prefix ${OPTICKS_EXTERNALS}/chlep/clhep_2.4.1.0.build
opticks-prepend-prefix ${OPTICKS_EXTERNALS}/xerces/build
opticks-prepend-prefix ${OPTICKS_EXTERNALS}/g4/geant4.10.06.p02.build
opticks-prepend-prefix ${OPTICKS_EXTERNALS}/boost/boost_1_70_0

## NB changing any directory paths demands an opticks-full rebuild
## This is enforced by $OPTICKS_PREFIX/bin/opticks-setup.sh  which
## is generated by opticks-full with opticks-setup-generate.

opticks-check-prefix
[ $? -ne 0 ] && echo ABORT && sleep 1000000000


oed(){ vi $BASH_SOURCE && ofu ; }
ofu(){ source $BASH_SOURCE ; }

path(){ echo $PATH | tr ":" "\n" ; }
paths(){
   local vars="CMAKE_PREFIX_PATH PKG_CONFIG_PATH PATH LD_LIBRARY_PATH DYLD_LIBRARY_PATH"
   local var
   for var in $vars ; do
       echo $var
       echo ${!var} | tr ":" "\n"
       echo
   done
   env | grep OPTICKS | grep PREFIX
}
